---
- hosts: localhost
  roles:
    - role: docker
      become: yes
    - role: ide
      become: yes
  tasks:
    - name: Now update my bashrc file (git branch display and docker cleanup)
      blockinfile:
        #become: false
        dest: "{{ lookup('env','HOME') }}/.bashrc"
        marker: "# {mark} Git branch display Bashrc  modifications"
        block: |
          parse_git_branch() {
            git branch 2> /dev/null | sed -e '/^[^*]/d' -e 's/* \(.*\)/(\1)/'
          }
          export PS1="\u@\h \[\e[32m\]\w \[\e[91m\]\$(parse_git_branch)\[\e[00m\]$"
        backup: yes
  #Update my ubuntu apt packages
    - name: Update and upgrade apt packages
      become: true
      apt:
        upgrade: yes
        update_cache: yes
        cache_valid_time: 86400 #One day
    - name: Install git/gitk/vim/gnome-shell-extensions/ncdu packages
      become: true
      package:
        name:
          - git
          - gitk
          - vim
          - gnome-shell-extensions
          - ncdu
          - yamllint
          - ansible-lint
        state: present
...
