---
  - name: Install aptitude using apt
    become: true
    apt: name=aptitude state=latest update_cache=yes force_apt_get=yes
  - name: Install required system packages
    apt: name={{ item }} state=latest update_cache=yes
    loop: [ 'apt-transport-https', 'ca-certificates', 'curl', 'software-properties-common', 'python3-pip', 'virtualenv', 'python3-setuptools']

  - name: Add Docker GPG apt Key
    apt_key:
      url: https://download.docker.com/linux/ubuntu/gpg
      state: present

  - name: Add Docker Repository
    apt_repository:
      repo: deb https://download.docker.com/linux/ubuntu bionic stable
      state: present

  - name: Update apt and install docker-ce
    apt: update_cache=yes name=docker-ce state=latest

  - name: Now update Bashrc file (docker cleanup function to free memory space)
    blockinfile:
      dest: "{{ lookup('env','HOME') }}/.bashrc"
      marker: "# {mark} Docker modifications"
      block: |
         #Used to cleanup dangling images and volumes
         function cleanup_docker() {
           docker ps -f status=exited -q | xargs -r docker rm
           docker images -f dangling=true -q | xargs -r docker rmi
           docker volume ls -qf dangling=true | xargs -r docker volume rm
         }
      backup: yes